[package]
name = "hello-heroku-actix"
version = "0.1.0"
authors = ["Aulia Widyaputra"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-cors = "0.5.3"